server {
    listen 80;
    server_name _;
    include /etc/nginx/mime.types;

    location / {
        root /app;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Opcional: Cache para o JSON do Instagram para não sobrecarregar
    location /src/data/ {
        root /app;
        add_header Cache-Control "no-cache, must-revalidate";
    }
}
